config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/index'

  resources :subscribers
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  

   root 'home#index'
   

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
validates :email, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@subscriber = Subscriber.new
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        SubscriberMailer.welcome_email(@subscriber).deliver
        format.html { redirect_to root_path, notice: 'Subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>Ease Insurance</title>
<!-- Bootstrap -->
<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">
<link href="css/flaticon.css" rel="stylesheet">
<link href="css/font-awesome.min.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,800italic,800,700italic,700,600italic,600,300italic,300,400italic' rel='stylesheet' type='text/css'>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<style>
/* Removes the default 20px margin and creates some padding space for the indicators and controls */
.carousel {
  margin-bottom: 0;
  padding: 0 40px 30px 40px;
}
/* Reposition the controls slightly */
.carousel-control {
  left: -12px;
}
.carousel-control.right {
  right: -12px;
}
/* Changes the position of the indicators */
.carousel-indicators {
  right: 50%;
  top: auto;
  bottom: 0px;
  margin-right: -19px;
}
/* Changes the colour of the indicators */
.carousel-indicators li {
  background: #c0c0c0;
}
.carousel-indicators .active {
  background: #333333;
}
.underconstruction .item {
  background:#1757b8;
  padding:20px;
  color:#fff;
  border-radius:5px;
  line-height:22px
}
.carousel-indicators {
  bottom: -20px;
}
.carousel {
  margin-bottom: 0;
  padding:30px 0;
}
.carousel-control {
  top: 45%;
  font-size:20px
}
.input-group .form-control {
  height:40px;
  border:0
}
.btn-default {
  background-color: #62bd18;
  border-color: #62bd18;
  color: #fff;
  height: 40px;
  border-radius:0 4px 4px 0;
  border:0;
  font-weight:bold
}
.btn-default a {
  color: #fff;
}
</style>
</head>
<body style="background:#71a9ff">
<header style=" background:#edffdf">

  <div class="container">
  <%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center"> <a href="#" class="logo"><img src="assets/logo2.png" alt=""></a> </div>
    </div>
  </div>
</header>
<div class="container">
  <h2 class="text-center" style="margin:40px 0; color:#c6ff9a">Stay tuned... We are launching soon</h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <p><strong>Subscribe to get updates</strong></p>
     <div class="form-group">
    <label for="emial">Email</label>
    <%= f.text_field :email,:class=>"form-control"%>
    <br>
    <button type="submit" class="btn btn-default">Subscribe</button>
  </br>
  <% end %>
  </div>
  
      <div id="myCarousel" class="carousel slide underconstruction">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <!-- Carousel items -->
        <div class="carousel-inner">
          <div class="item active">
            <h3>Insurance, no more a complex word...</h3>
            <p> We are actively transforming the future of Insurance to create a resilient market of transparency, trust and capital strength. We are challenging the norm by combining a innovative design thinking approach with exceptional industry expertise and smart technology.</p>
                                                       
         </div>
          <!--/item-->
          <div class="item">
            <p> Whether you are looking to outsource your day-to-day insurance administration or need expertise for a one-off project, Ease Insurance can provide you the Solution. With experienced and experts in a wide range of insurance, we offer specialist advice tailored to your exact requirements. From devising effective insurance programmes, to taking care of complex claim negotiations and advising on major finance deals, we have the insight, focus and vision you need to achieve your objectives. </p>
          </div>
          <!--/item-->
          <div class="item">
                 <p> Our aim is to provide a totally independent service to consumers and users of insurance in India.
                Understanding insurance and being informed is the key to getting the most from your policy and avoiding unexpected problems. </p>
             
          </div>
          <!--/item-->
        </div>
        <!--/carousel-inner-->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a> <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a> </div>
      <!--/myCarousel-->
    </div>
  </div>
</div>
<!-- Return to Top -->
<a href="javascript:" id="return-to-top"><span aria-hidden="true" class="glyphicon glyphicon-chevron-up"></span></a>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
<script type="text/javascript">
  // ===== Scroll to Top ==== 
$(window).scroll(function() {
    if ($(this).scrollTop() >= 50) {        // If page is scrolled more than 50px
        $('#return-to-top').fadeIn(200);    // Fade in the arrow
    } else {
        $('#return-to-top').fadeOut(200);   // Else fade out the arrow
    }
});
$('#return-to-top').click(function() {      // When arrow is clicked
    $('body,html').animate({
        scrollTop : 0                       // Scroll to top of body
    }, 500);
});
  </script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Easeinsurance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/subscribers/_form.html.erb
<%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing Subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subscribers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.email %></td>
        <td><%= link_to 'Show', subscriber %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<h1>New Subscriber</h1>

<%= render 'form' %>

<%= link_to 'Back', subscribers_path %>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscriber.email %>
</p>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>